name: PushACR

on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
  
    steps:
    - name: Chekout code
      uses: actions/checkout@v4
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image
      env:
        ACR_NAME: ${{ secrets.ACR_NAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      run: |
        docker build -t $ACR_NAME.azurecr.io/myimage:${{ github.sha }} .
        echo $ACR_PASSWORD | docker login $ACR_NAME.azurecr.io -u $ACR_NAME --password-stdin
        docker push $ACR_NAME.azurecr.io/myimage:${{ github.sha }}
