name: PushACR

on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
  
    steps:
    - name: Chekout code
      uses: actions/checkout@v4
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Set date
      id: set-date
      run: echo "::set-output name=date::$(date +%Y%m%d%H%M)"

    - name: Build and push Docker image
      env:
        ACR_NAME: ${{ secrets.ACR_NAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        CURRENT_DATE: ${{ steps.set-date.outputs.date }}
      run: |
        docker build -t $ACR_NAME.azurecr.io/appgastos:${CURRENT_DATE} .
        echo $ACR_PASSWORD | docker login $ACR_NAME.azurecr.io -u $ACR_NAME --password-stdin
        docker push $ACR_NAME.azurecr.io/appgastos:${CURRENT_DATE}
